-- MySQL Script generated by MySQL Workbench
-- Mon Jan 30 19:22:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nikken
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nikken` DEFAULT CHARACTER SET utf8 ;
USE `nikken` ;

-- -----------------------------------------------------
-- Table `nikken`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nikken`.`users` ;

CREATE TABLE IF NOT EXISTS `nikken`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nikken_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `language` VARCHAR(2) NOT NULL DEFAULT 'en',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nikken_id_UNIQUE` (`nikken_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
)
ENGINE = InnoDB;

INSERT INTO `users` (`nikken_id`, `name`, `language`)
VALUES ('1', 'John Doe', 'EN');

-- -----------------------------------------------------
-- Table `nikken`.`stages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nikken`.`stages` ;

CREATE TABLE IF NOT EXISTS `nikken`.`stages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `image_route` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `code_index` (`code` ASC) VISIBLE
)
ENGINE = InnoDB;

INSERT INTO `stages` (`code`, `name`,`description`, `image_route`)
VALUES (1, 'Learn', 'Start your first 48 hours with Nikken by quickly learning the business basics of enrolling and retailing. Familiarize yourself with myNikken.com (your back office) where you can access the Incentives Program, the Compensation Plan and your business tools, including the 30-Day Journey and the 90-Day Planner.', ''), 
(2, 'Plan', 'Build your business plan by setting goals for the next 30 days. Use the <br>Yes! My Wellness Home</br> to send out links to everyone on your contact list. Make sure you create your personal story to share, including your "why" for being part of the Nikken Global Wellness Community.', ''),
(3, 'Do', "DESCRIPTION", ''), 
(4, 'Grow', 'The 90-Planner is the business-building tool that helps keep you on track. Use it every day to move forward and remember always to water and nurture the seeds you have planted with a consistent follow-up schedule with your contacts.', '');

-- -----------------------------------------------------
-- Table `nikken`.`levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nikken`.`levels` ;

CREATE TABLE IF NOT EXISTS `nikken`.`levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `stage_code` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `video_url` VARCHAR(255) NOT NULL,
  `pdf_url` VARCHAR(255) NOT NULL,
  `image_route` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`code`, `stage_code`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `levels_stage_code_index` (`stage_code` ASC) VISIBLE,
  CONSTRAINT `levels_stage_code_constraint`
    FOREIGN KEY (`stage_code`)
    REFERENCES `nikken`.`stages` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

INSERT INTO `levels` (`code`, `stage_code`, `title`, `description`, `video_url`, `pdf_url`, `image_route`)
VALUES 
  (1, 1, 'BUSINESS BASICS<br><p>(Enrolling + Retailing)</p>', 'Two key components comprise your Nikken 
  business:<br>
  <ul>
    <li>Enrolling (developing an organization)</li>
    <li>Retailing (acquiring and serving customers)</li>
  <ul>
  <br><b>1.1 Enrolling</b><br>
  The Enrolling component is designed to maximize business growth and compensation.<br>It involves establishing at least three 
  key frontline business partners (Consultants) who each want to develop their own Nikken business. Keep in mind that you may need 
  to sponsor many people in order to find your three frontline partners. The best way to get started is an ABC.<br><br>
  <b>1.2 Retailing</b><br> The Retailing component is important for ensuring income.<br>Not everyone you approach will want to start a Nikken business, but many of them have the potential to become great customers. Set a goal to develop two to five retail customers each month. Their regular use of Nikken products through Autoship will help create consistent monthly volume.<br> 
  Combined, these two components form the framework for your success with your Nikken Business. As you assist your key partners to 
  duplicate their business, you will build a business that generates the freedom and prosperity you desire.',
  'https://www.youtube.com/embed/IS59OH5Q748','https://drive.google.com/drive/u/0/folders/1nVhc_GuDaavQQgSMHC2J5TeCn8l-JJhZ', ''), 
  (2, 1, 'BUSINESS TOOLS<br><p>(Back Office)<p>', 
  "Get Familiar with your Back Office. www.MyNikken.com. Learn how to:<br>
  <ul>
    <li>Enroll a Customer</li>
    <li>Place an Order</li>
    <li>Set up a Wellness Subscription</li>
    <li>Create Product Links</li>
    <li>Locate Transaction History</li>
    <li>Locate Order History</li>
    <li>Connect to Social Groups</li>
  </ul>
  Learn about:<br>
  <ul>
    <li>Quick Links</li>
    <li>Calendar (Upcoming Events)</li>
    <li>Tools</li>
    <li>Incentives</li>
  </ul>
  Now that you are familiar with the basic tools necessary to get started, let's talk about the PowerHouse, 18K Club, Mentor Club, 
  Mentor Elite Club, Travel Club & Lifesyle Bonus Incentive Programmes and the Wellness Home Packs.<br>
  Please check the Incentives and the Wellness Home Pack information in your back office.", 
  'https://www.youtube.com/embed/S4i1fHt5NLw', 'https://drive.google.com/drive/u/0/folders/1nVhc_GuDaavQQgSMHC2J5TeCn8l-JJhZ', ''),
  (3, 1, 'BUSINESS TOOLS<br><p>(Share App)</p>', "2.1 billion people have a Smartphone and statistics show that many of 
  them use their devices up to 264 times a day! That's an incredible base of potential prospects! All you have to do is download 
  the Nikken Share app on your Smartphone and use it.
  Nikken has set up an entire experience for you to Share. You'll be able to:<br>
  <ul>
    <li>Conduct business activities</li>
    <li>Manage prospects</li>
    <li>Nurture leads by sharing information directly</li>
    <li>Make sales</li>
    <li>Sign up newcomers</li>
    <li>Post on social media</li>
    <li>Share videos</li>
  </ul>
  The Nikken Share app will even notify you when your shared media is viewed! You can also choose to purchase credits through the 
  shopping cart to use the built-in sampling program.", 
  'https://www.youtube.com/embed/6ICaxaoKEs0', 'https://drive.google.com/drive/u/0/folders/1nVhc_GuDaavQQgSMHC2J5TeCn8l-JJhZ', ''),
  (4, 1, 'INCENTIVES 2023', "The 2023 Nikken Incentive Program is designed to guide business builders through a process that will help
  establish a strong business structure. These incentives will support the creation of new Consultants and
  teams.<br><br>
  The incentive program is in addition to the Compensation Plan and incentivizes and guides you as part of a business
  training process that is easy to follow and understand. As you grow your business, you'll be rewarded with your efforts
  every step of the way and you'll also be changing the lives of those in your team and the wellness of your customers too.
  Let's celebrate you and your achievements!", 
  '', 'https://drive.google.com/drive/u/0/folders/1LX_SfIm5dwIAhXqZUNSioLJRH8KurGpx', '/images/pdf-img/pdf1-4.jpg'),
  (5, 1, 'COMPENSATION PLAN', 'Through its generous compensation plan, Nikken offers different ways to earn. Your 
  success and the income you earn from your Nikken business is determined by the number of customers you have, the amount that 
  each customer purchases and your effectiveness in building a sales organization that includes other Consultants who help you 
  expand your customer base as they build their own sales organizations. This compensation plan is available to Nikken Consultants 
  and International Consultants.', 
  '', 'https://drive.google.com/file/d/1ZBDjdRV1zdSljpp9rF4ZO9BHaWvKUjpy/view?usp=sharing', '/images/pdf-img/pdf1-5.jpg'),
  (6, 1, '30-DAY JOURNEY ', 'The 30-Day Journey is the perfect guideline to invite especially new Consultants 
  onboard. It takes you to the core of the activities needed to develop your business and achieve great success. <br>The goal of 
  the 30-Day Journey is to complete at least one PowerHouse incentive and achieve the new rank of Silver.', 
  '', 'https://slfil.nikken.com/WeStart/30%20Day%20Journey%20-12%20Jan%202023%20V1%20EN.pdf', '/images/pdf-img/pdf1-6.jpg'),
  (7, 1, '90-DAY PLANNER', 'A successful Nikken business runs on a recurring 90-day cycle. You establish your quarterly short-term goals, plan your daily, 
  weekly and monthly activities and then repeat this successful cycle every 90 days to ultimately achieve your long-term goals.
  The 90-day planner is designed to help you focus, motivate and organize your team, so you can manage your business more efficiently 
  and effectively. It is an excellent tool to help make this happen.<br><br>
  Use it to:<br>
  Define your goals<br>
  Identify key areas to focus on<br>
  Monitor your progress in achieving objectives',
  '', 'https://slfil.nikken.com/WeStart/90%20Day%20Planner%20EN%20-%20April%2010%202023.pdf', '/images/pdf-img/pdf1-7.jpg'),
  (1, 2, 'NIKKEN WELLNESS HOME', 'The idea that your home should be the healthiest, happiest and safest environment for you and your family to live in; our overall 
  wellbeing has a lot to do with our lifestyles and Nikken believes improving five interrelated areas to support a Wellness Home:<br>
  * Sleep<br>
  * Water<br>
  * Air<br>
  * Nutritionals and Skincare<br>
  * Natural Energies <br><br>
  These areas are the foundation of our lives and are vital to our health and wellbeing.', 
  '', 'https://drive.google.com/drive/u/0/folders/1gNLI28veRFnGWx7BMvS_Na0B_1S-gHmx', ''),
  (2, 2, 'YES! MY WELLNESS HOME', "When your potential customers click on the link, they will be taken to the Yes, My Wellness Home 
  site. They will see your name and email information on that site.<br>
  To take advantage of this offer, your potential customer must order at least two products and spend a minimum of US $350 / CAN $430 
  to obtain the 10% discount. In addition, all orders for more than US or CAN $500 will qualify for free shipping!<br>
  Your potential customer will need to 'Sign Up' as a Registered Customer to proceed with the order. This is a one-time link and expires 
  within 15 days of issue.<br>
  The Yes, My Wellness Home site offers most of the Nikken product range, except those that can be purchased on Wellness Subscriptions, 
  such as Filters and Nutritionals. (Skin care is the exception and is available).<br>
  You can track all links that you've sent below.", 
  '', 'https://drive.google.com/drive/u/0/folders/1gNLI28veRFnGWx7BMvS_Na0B_1S-gHmx', ''),
  (3, 2, 'CREATE YOUR STORY', "Crafting your story is is a powerful way to illustrate your message. Craft refers to the artistic skill 
  or technique with which a Consultant puts together a narrative and other elements to convey meaning and produce an effect.<br>
  By sharing our stories, we engage, connect, and build trust and understanding of each other's experiences. Storytelling is essential to 
  everyday life; it helps convey purpose, increase loyalty, and deepen relationships.<br>
  Convincing stories can help us take action or make decisions, as they appeal to us not only on a rational level but also on an emotional 
  level. Crafting stories is an effective tool to use when building your business.", 
  'https://www.youtube.com/embed/O-f7NZ99Bl8', 'https://slfil.nikken.com/WeStart/Crafting%20Story%20Steps%20-%20Mar%206%2023.pdf', ''),
  (4, 2, 'CONTACT LIST', 'The Contact List is an exercise to help us determine who we have as potential customers or consultants in our circle of influence (family, friends, colleagues, coworkers, etc.). Then, through this list, we can start working right away.
<br>Our Contact List will be important in starting our business journey; the more contacts or names in our list, the better. Do not exclude anyone; give all your people a chance to know your new business. Again, the more contacts in your list, the better off you will be.', 
  '', 'https://slfil.nikken.com/WeStart/Contact_List_1_18-Apr-23_V6.pdf', '/images/pdf-img/pdf2-2.jpg'),
  (5, 2, "ABC's", 'What is an ABC? <br><br>
  The purpose of an ABC is to leverage the expertise of your sponsor or more experienced Wellness Entrepreneur with your contact while you 
  listen, learn, and take notes.<br>
  The benefits of an ABC: simplicity - anyone can do it. New Wellness Entrepreneurs do not need to know everything. Contacts hear varied 
  perspectives and get introduced to other Wellness Entrepreneurs on team or in network.', 
  'https://www.youtube.com/embed/khTyT--u5_0','https://slfil.nikken.com/WeStart/ABC_s%20EN%20-%20Feb%2015%2023.pdf', ''),
  (6, 2, 'PLAN 30-DAYS GOALS', 'Plan to achieve the goal of the 30-Day Journey to complete at least one PowerHouse incentive and achieve 
  the new rank of Silver.', 
  '', 'https://slfil.nikken.com/WeStart/Plan_for_the_30-days_(since_week_1)_18-Apr-23_V7.pdf', '/images/pdf-img/pdf2-5.jpg'),
  (7, 2, 'PLAN 90-DAYS GOALS', 'Plan to achieve the goal of the 90-Day Planner to achieve 18K CLUB (One Silver per Month)  or go to the 
  next level according to your Rank and needs. Check your 90 Day Planner and add any other goals you will like to work on to become a 
  succesfull entrepreneur.', 
  '', 'https://slfil.nikken.com/WeStart/Plan_for_the_90-days_(since_week_1)_18-Apr-23_V8.pdf', '/images/pdf-img/pdf2-6.jpg'),
  (1, 3, 'TIME FOR ACTION!', 
  'Get together with your Sponsor / Mentor to follow up on your weekly activities to achieve your goals at the end of the month with either a Powerhouse or a new rank.<br>
  Be ready to share your story.<br><br>
  Schedule ABCs with your Sponsor and your list of Contacts.<br>
  Be sure to leverage Social Media channels such as Telegram, Whatsapp, Facebook, Instagram, etc. to expand your contact list.<br>
  For addtional information that can help you develop the rhythm of your business join: Nikken Next, Kickoff Call, Seiko Kai, Master Day and HBM.', 
  '', 'https://drive.google.com/file/d/1ndrWQmb7L0ZZeOcKdXqAJCF5bpvLYbfn/view', '/images/pdf-img/pdf3-1.jpg'),
  (2, 3, 'REVIEW & REDIRECT GOALS', '30 DAYS GOALS', 
  '', 'https://docs.google.com/document/d/17w57yfmQ_mDE0wSUlLptJpIBrSbVMhG7B7YPa8LxfmA/edit?usp=sharing', '/images/pdf-img/pdf3-2.jpg'),
  (1, 4, 'FOLLOW-UP 90-DAY PLANNER', 'Focus on achieving the 18k Club.<br>
  "Help your 3 frontline to achieve the silver rank."<br><br>
  Review & redirect goals if necessary.<br>
  Once you achieve your powerhouse and the 18k club incentive you are ready for the next level! Which is qualify for the mentor club and the mentor elite club.', 
  '', 'https://docs.google.com/document/d/1vGiKO-uY0qMkZ0aVE-5azx3iC7nJjjPTzFIYAHmkXfc/edit?usp=sharing', '/images/pdf-img/pdf4-1.jpg');

-- -----------------------------------------------------
-- Table `nikken`.`users_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nikken`.`users_progress` ;

CREATE TABLE IF NOT EXISTS `nikken`.`users_progress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_nikken_id` VARCHAR(45) NOT NULL,
  `stage_code` INT NOT NULL,
  `level_code` INT NOT NULL,
  `is_content_read` BOOLEAN NOT NULL,
  `is_video_watched` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `users_progress_stage_code_index` (`stage_code` ASC) VISIBLE,
  CONSTRAINT `users_progress_stage_code_constraint`
    FOREIGN KEY (`stage_code`)
    REFERENCES `nikken`.`stages` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `users_progress_user_nikken_id_index` (`user_nikken_id` ASC) VISIBLE,
  CONSTRAINT `users_progress_user_nikken_id_constraint`
    FOREIGN KEY (`user_nikken_id`)
    REFERENCES `nikken`.`users` (`nikken_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `users_progress_level_code_index` (`level_code` ASC) VISIBLE,
  CONSTRAINT `users_progress_level_code_constraint`
    FOREIGN KEY (`level_code`)
    REFERENCES `nikken`.`levels` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

INSERT INTO `users_progress` (`user_nikken_id`, `stage_code`, `level_code`, `is_content_read`, `is_video_watched`)
VALUES ('1', '1', '1', false, false);

-- -----------------------------------------------------
-- Table `nikken`.`users_progress_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nikken`.`users_progress_logs` ;

CREATE TABLE IF NOT EXISTS `nikken`.`users_progress_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_nikken_id` VARCHAR(45) NOT NULL,
  `stage_code` INT NOT NULL,
  `level_code` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `request_ip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `users_progress_logs_stage_code_index` (`stage_code` ASC) VISIBLE,
  CONSTRAINT `users_progress_logs_stage_code_constraint`
    FOREIGN KEY (`stage_code`)
    REFERENCES `nikken`.`stages` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `users_progress_logs_user_nikken_id_index` (`user_nikken_id` ASC) VISIBLE,
  CONSTRAINT `users_progress_logs_user_nikken_id_constraint`
    FOREIGN KEY (`user_nikken_id`)
    REFERENCES `nikken`.`users` (`nikken_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `users_progress_logs_level_code_index` (`level_code` ASC) VISIBLE,
  CONSTRAINT `users_progress_logs_level_code_constraint`
    FOREIGN KEY (`level_code`)
    REFERENCES `nikken`.`levels` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
